"""Added Questions table

Revision ID: 46a429de3859
Revises: 
Create Date: 2022-02-02 17:43:28.395054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a429de3859'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_category', sa.String(length=30), nullable=False),
    sa.Column('choice1', sa.String(length=150), nullable=True),
    sa.Column('choice2', sa.String(length=150), nullable=True),
    sa.Column('choice3', sa.String(length=150), nullable=True),
    sa.Column('choice4', sa.String(length=150), nullable=True),
    sa.Column('choice5', sa.String(length=150), nullable=True),
    sa.Column('image1', sa.String(length=150), nullable=True),
    sa.Column('image2', sa.String(length=150), nullable=True),
    sa.Column('image3', sa.String(length=150), nullable=True),
    sa.Column('image4', sa.String(length=150), nullable=True),
    sa.Column('image5', sa.String(length=150), nullable=True),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('other_answer', sa.String(length=250), nullable=True),
    sa.Column('active_flag', sa.String(length=10), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('qn_creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['qn_creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
